config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resource :user, only: [:edit, :update]
  resources :comments
  get 'pages/info'
  
  resources :ideas
  root 'ideas#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :idea
    belongs_to :user
    validates_presence_of :user_name, :body
    mount_uploader :picture, PictureUploader
end

app/models/idea.rb
class Idea < ApplicationRecord
    mount_uploader :picture, PictureUploader
    has_many :comments
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
include Gravtastic
gravtastic 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :ideas
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper
    protect_from_forgery with: :exception
    before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    @idea = Idea.find_by_id @comment.idea_id
    @comments = @idea.comments.all
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to idea_path(@comment.idea_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :template => "ideas/show" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_name, :body, :idea_id, :picture, :reply_id, :user_id)
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @comments = @idea.comments.order(like_count: :desc).all
    @comment = @idea.comments.build
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture, :user_id, :sub_content)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users/1/edit
  def edit
    @user = current_user
  end
  
  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = current_user
    
    if @user.update(user_params)
      redirect_to root_path, notice: 'Profile was successfully updated.'
    else
    render :edit
  end
    
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_name, :telephone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user)
  # thsi
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true, :html => {:multipart => true}) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form.hidden_field :idea_id %>
  <%= form.hidden_field :user_id, value: current_user.id %>
  
  <div class="form-group">
    <%= form.label :user_name %>
    <%= form.text_field :user_name, class: "form-control", style: "width: 100%", required: 1 %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control", required: 1 %>
  </div>
  
  <div class="form-group">
    <%= form.label :picture %><br>
    <%= form.file_field :picture, required: 1 %>
  </div>
  
  <div class="form-group row">
      <div id="image-preview"></div>
  </div>
  
  <div class="form-group">
    <%= form.submit "Send Comment", class: "btn btn-success" %>
  </div>
<% end %>

<script type="text/javascript">
$('#comment_picture').change(function () {
        if (typeof (FileReader) != "undefined") {
            var dvPreview = $('#image-preview');
            dvPreview.html('');
            var regex = /^([a-zA-Z0-9\s_\\.\-:])+(.jpg|.jpeg|.gif|.png|.bmp)$/;
            $($(this)[0].files).each(function () {
                var file = $(this);
                if (regex.test(file[0].name.toLowerCase())) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        var img = $("<img />");
                        img.attr("src", e.target.result);
                        img.attr("class", "col-xs-4 img");
                        dvPreview.append(img);
                    }
                    reader.readAsDataURL(file[0]);
                } else {
                    swal(file[0].name + " is not a valid image file.");
                    dvPreview.html('');
                    return false;
                }
            });
        } else {
            swal('This browser does not support HTML5 FileReader.');
        }
    });
</script>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Body</th>
      <th>Idea</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.idea_id %><%= comment.picture %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @comment.user_name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Idea:</strong>
  <%= @comment.idea_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/ideas/_form.html.erb
<% content_for :ideas_class, "active" %>
<%= form_with(model: idea, local: true, class: "form-horizontal") do |form|%>
  <% if idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user.id %>
  
  <div class="form-group">
    <%= form.label :name, class: "col-md-3 control-label" %>
    <div class="col-md-6">
        <%= form.text_field :name, class: "form-control", style: "width: 100%", required: 1 %>
    </div>
  </div>
  
  <div class="form-group">
    <%= form.label :sub_content, class: "col-md-3 control-label" %>
    <div class="col-md-6">
        <%= form.text_area :sub_content, class: "form-control", required: 1 %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :description, class: "col-md-3 control-label" %>
    <div class="col-md-6">
        <%= form.text_area :description, class: "form-control", required: 1 %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :picture, class: "col-md-3 control-label" %>
    <div class="col-md-6">
        <%= form.file_field :picture %>
    </div>
  </div>
  
  
  <div class="form-group row">
      <div id="image-preview" class="col-md-offset-3 col-md-6">
        <%= image_tag(@idea.picture_url, width: 150, class: "img img-reponsive") if @idea.picture.present? %>
      </div>
  </div>
 
  <div class="actions form-group">
    <div class="col-md-offset-3 col-md-6">
        <%= form.submit yield(:button_text), class: "btn btn-success" %>
        <%= link_to 'Back', ideas_path, class: "btn btn-warning" %>
    </div>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<% provide :button_text, "Edit" %>
<h1 style="text-align: center">Editing Idea</h1>

<%= render 'form', idea: @idea %>


<script type="text/javascript">
$('#idea_picture').change(function () {
        if (typeof (FileReader) != "undefined") {
            var dvPreview = $('#image-preview');
            dvPreview.html('');
            var regex = /^([a-zA-Z0-9\s_\\.\-:])+(.jpg|.jpeg|.gif|.png|.bmp)$/;
            $($(this)[0].files).each(function () {
                var file = $(this);
                if (regex.test(file[0].name.toLowerCase())) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        var img = $("<img />");
                        img.attr("src", e.target.result);
                        img.attr("class", "col-xs-4 img");
                        dvPreview.append(img);
                    }
                    reader.readAsDataURL(file[0]);
                } else {
                    swal(file[0].name + " is not a valid image file.");
                    dvPreview.html('');
                    return false;
                }
            });
        } else {
            swal('This browser does not support HTML5 FileReader.');
        }
    });
</script>

app/views/ideas/index.html.erb
<% content_for :ideas_class, "active" %>
<div class="row">
    <div class="col-lg-12">
        <h3 class="text-center" style="border-bottom: 1px solid #333; padding-bottom: 20px">
            All your ideas
        </h3>
        <div class="pull-right">
            <%= link_to new_idea_path do %>
              <span class="glyphicon glyphicon-plus"></span> New Idea
            <% end %>
            
            <%= link_to ideas_path do %>
              <span class="glyphicon glyphicon-list"></span> All Ideas
            <% end %>
        </div>
        
        <ul class="timeline">
            <% @ideas.each do |idea| %>
                <li>
                  <div class="timeline-image">
                    <%= image_tag(idea.picture_url, width: 200, height: 200, class: "img-circle img-responsive") if idea.picture.present? %>
                  </div>
                  <div class="timeline-panel">
                    <div class="timeline-heading">
                      <h4><%= idea.name %></h4>
                      <h4 class="subheading"></h4>
                    </div>
                    <div class="timeline-body">
                      <p class="text-muted">
                        <%= idea.sub_content %>
                      </p>
                      <%= link_to 'Show Details', idea %>
                    </div>
                  </div>
                  <div class="line"></div>
                </li>
            <% end %>
        </ul>
    </div>
</div>

app/views/ideas/new.html.erb
<% provide :button_text, "Create" %>
<h1 class="text-center">New Idea</h1>

<%= render 'form', idea: @idea %>

app/views/ideas/show.html.erb
<% content_for :ideas_class, "active" %>
<div class="row idea-content">
    <div class="">
        
        <div class="col-md-12">
            <h2>
              <%= @idea.name %>
            </h2>
        </div>
        
        <div class="col-md-3 img-box">
            <%= image_tag(@idea.picture_url, width: '100%') if @idea.picture.present? %>
        </div>
        
        <div class="col-md-9">
            <div class="action-group pull-right">
                <ul>
                    <li>
                        <span class="glyphicon glyphicon-list"></span>
                        <%= link_to 'All Ideas', ideas_path, class: "action-title" %>
                    </li>
                    <li>
                        <span class="glyphicon glyphicon-pencil">
                        </span><%= link_to 'Edit', edit_idea_path(@idea), class: "action-title" %>
                    </li>
                </ul>
            </div>
            <div class="pull-left">
                <h4>
                  <strong><%= @idea.sub_content %></strong>
                </h4>
                <article>
                    <%= @idea.description %>
                </article>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="page-header">
            <h3 style="border-bottom: 1px solid #000000">
                <small class="pull-right"><%= @comments.count %> comments</small> Comments
            </h3>
        </div>
        <div class="comments-list">
            <% @comments.each do |comment| %>
                <div class="media">
                    <div class="media-left">
                        <%= image_tag(comment.picture_url, width: 40) if comment.picture.present? %>
                    </div>
                    <div class="media-body">
                        
                      <h4 class="media-heading user_name"><%= comment.user_name %></h4>
                      <%= comment.body %>
                      
                    </div> 
                </div>
            <% end %>
        </div>
    </div>
    
    <div class="col-md-6">
        <h3 style="border-bottom: 1px solid #000000">Write Comment</h3>
        <%= render 'comments/form', comment: @comment %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsgirls</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap-theme.min.css" />
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">
            <span class="glyphicon glyphicon-gift"></span>
            The Idea app
          </a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
                <li class="<%= yield (:ideas_class) %>"><a href="/ideas">Ideas</a></li>
                <li class="<%= yield (:info_class) %>"><a href="/pages/info">Info</a></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle text-white" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" class="">
                    
                    <%= current_user.user_name || current_user.email %> <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <li class="img-user">
                        <%= image_tag current_user.gravatar_url, :class=> "img img-circle" %>
                    </li>
                    <li>
                        <%= link_to edit_user_registration_path, :class => 'navbar-link' do %>
                          <span class="glyphicon glyphicon-lock"></span> Edit Password
                        <% end %>
                    </li>
                    <li>
                        <%= link_to edit_user_path, :class => 'navbar-link' do %>
                          <span class="glyphicon glyphicon-user"></span> Edit Profile
                        <% end %>
                    </li>
                    <li>
                        <%= link_to destroy_user_session_path, :class => 'navbar-link', method: :delete do %>
                          <span class="glyphicon glyphicon-arrow-left"></span> Logout
                        <% end %>
                    </li>
                  </ul>
                </li>
            <% else %>
                <li>
                    
                    <%= link_to new_user_registration_path, :class => 'navbar-link' do %>
                      <span class="glyphicon glyphicon-plus"></span> Sign Up
                    <% end %>
                    
                </li>
                <li>
                    <%= link_to new_user_session_path, :class => 'navbar-link' do %>
                        <span class="glyphicon glyphicon-arrow-right"></span> Sign In
                    <% end %>
                </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container" style="min-height: 410px">
        <% if notice %>
            <div class="alert alert-success alert-dismissible fade in">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Success!</strong> <%= notice %>.
            </div>
        <% end %>
        <% if alert %>
            <div class="alert alert-warning alert-dismissible fade in">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Warning!</strong> <%= alert %>.
            </div>
        <% end %>
        <%= yield %>
    </div>
    <div class="footer">
        <footer>
            Rails Girls <%= Time.now.year %>
        </footer>
    </div>
    

    <script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/pages/info.html.erb
<% content_for :info_class, "active" %>
<h1>Introduce Yourself</h1>
<p>
    <article>
        <b>My name: </b>
        <p>Bui Thi Hieu</p>
        
        <p>I come from Ha Tinh, Viet Nam.</p>
    </article>
</p>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 style="text-align: center">Editing Profile</h1>
<div class="col-md-4 col-md-offset-4">
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this idea from being saved:</h2>
    
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="form-group">
        <%= f.label :user_name %><br>
        <%= f.text_field :user_name, class: "form-control", style: "width: 100%", placeholder: "Username" %>
      </div>
      <div class="form-group">
        <%= f.label :telephone %><br>
        <%= f.text_field :telephone, class: "form-control", style: "width: 100%", placeholder: "0123456789" %>
      </div>
      <div class="gravatar_edit">
        <%= gravatar_for current_user %>
        <a href="http://gravatar.com/emails" target="_blank" class="change-avatar">
            <span class="glyphicon glyphicon-cloud-upload"></span>Change Avatar</a>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
        <%= user.email %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>